# Generated by Django 3.2.9 on 2021-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=40)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
